Algoritmo "urna-eletronica"

Var
      numeroCandidato1: inteiro
      numeroCandidato2: inteiro
      numeroCandidato3: inteiro
      nomeCandidato1: caractere
      nomeCandidato2: caractere
      nomeCandidato3: caractere
      contCandidato1: inteiro
      contCandidato2: inteiro
      contCandidato3: inteiro
      contBranco: inteiro
      contNulo: inteiro
      voto: inteiro
      resposta: caractere
      i: inteiro


Inicio
      escreva("Informe o nome do candidato 1: ")
      leia(nomeCandidato1)
      escreva("Informe o número do candidato 1: ")
      leia(numeroCandidato1)

      limpatela

      escreva("Informe o nome do candidato 2: ")
      leia(nomeCandidato2)
      escreva("Informe o número do candidato 2: ")
      leia(numeroCandidato2)

      limpatela

      escreva("Informe o nome do candidato 3: ")
      leia(nomeCandidato3)
      escreva("Informe o número do candidato 3: ")
      leia(numeroCandidato3)

      limpatela

Fimalgoritmo