Algoritmo "urna-eletronica"

Var
      numeroCandidato1: inteiro
      numeroCandidato2: inteiro
      numeroCandidato3: inteiro
      nomeCandidato1: caractere
      nomeCandidato2: caractere
      nomeCandidato3: caractere
      contCandidato1: inteiro
      contCandidato2: inteiro
      contCandidato3: inteiro
      contBranco: inteiro
      contNulo: inteiro
      voto: inteiro
      resposta: caractere
      i: inteiro


Inicio

Fimalgoritmo